# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name_plural': 'debuggers',
            },
        ),
    ]
