# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/event_images')),
                ('background_colour', models.CharField(max_length=7)),
                ('description', models.TextField()),
                ('privacy', models.CharField(max_length=1)),
                ('show_remaining_tickets', models.BooleanField()),
                ('allow_resell', models.CharField(max_length=1)),
                ('when_resell', models.CharField(blank=True, max_length=1)),
                ('amount_resell', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tagline', models.TextField(max_length=64)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/organiser_images')),
                ('website', models.CharField(blank=True, max_length=256)),
                ('facebook', models.CharField(blank=True, max_length=256)),
                ('twitter', models.CharField(blank=True, max_length=256)),
                ('background_colour', models.CharField(blank=True, default='#D3D3D3', max_length=10)),
                ('text_color', models.CharField(blank=True, default='#000000', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisers',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales_start_date', models.DateField(blank=True, null=True)),
                ('sales_start_time', models.DateTimeField(blank=True, null=True)),
                ('sales_end_date', models.DateField(blank=True, null=True)),
                ('sales_end_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Organiser'),
        ),
    ]
