# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('start_time', models.DateField()),
                ('end_date', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/event_images')),
                ('description', models.TextField()),
                ('privacy', models.CharField(max_length=1)),
                ('show_remaining_tickets', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/organiser_images')),
                ('website', models.CharField(max_length=256)),
                ('facebook', models.CharField(max_length=256)),
                ('twitter', models.CharField(max_length=256)),
                ('background_colour', models.CharField(max_length=10)),
                ('text_color', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organisers',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales_start_date', models.DateField()),
                ('sales_start_time', models.DateTimeField()),
                ('sales_end_date', models.DateField()),
                ('sales_end_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Organiser'),
        ),
    ]
