# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_resell',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='when_resell',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organiser',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='background_colour',
            field=models.CharField(blank=True, default='#D3D3D3', max_length=10),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='facebook',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='twitter',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='website',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
