# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180205_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount_resell',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
