# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180205_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
