# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180205_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount_resell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
