# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180205_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sales_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
