# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20180205_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_colour',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
