# Generated by Django 2.0.1 on 2018-02-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_background_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='tagline',
            field=models.TextField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
