# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180227_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
