# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_orderticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='orderticket',
            name='user',
        ),
    ]
